# These are supported funding model platforms

github: NULL
patreon: NULL
open_collective: NULL
ko_fi: NULL
tidelift: NULL
community_bridge: NULL
liberapay: NULL
issuehunt: NULL
otechie: NULL
custom: NULL
